name: music_player
version: 1.0.2+3
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  on_audio_query: ^2.6.1
  we_slide: ^2.4.0
  palette_generator: ^0.3.3+1
  just_audio: ^0.9.29
  mini_music_visualizer: ^1.0.2
  rxdart: ^0.27.5
  marquee: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^4.1.1
  sleek_circular_slider: ^2.0.1
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.5
  just_audio_background: ^0.0.1-beta.7
  dio: ^4.0.6
  flip_card: ^0.6.0


dev_dependencies: 
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

